import { AddOnItem, CleaningTeam, PricingRulesConfig, BookingRecord } from "./types";

export const DEFAULT_PRICING_RULES: PricingRulesConfig = {
  baseRate: 120,
  perBedroom: 25,
  perBathroom: 35,
  sqftTiers: [
    { maxSqft: 1500, surcharge: 0 },
    { maxSqft: 2500, surcharge: 30 },
    { maxSqft: 3500, surcharge: 65 },
    { maxSqft: 99999, surcharge: 105 },
  ],
  typeMultipliers: {
    standard: 1.0,
    deep: 1.45,
    move_in_out: 1.65,
    post_construction: 1.90,
  },
  conditionMultipliers: {
    normal: 1.0,
    heavy: 1.25,
    extreme: 1.50,
  },
  conditionExtraHours: {
    normal: 0,
    heavy: 1.5,
    extreme: 3.0,
  },
  frequencyDiscounts: {
    one_time: 0.0,
    monthly: 0.10,
    biweekly: 0.15,
    weekly: 0.20,
  },
  depositPercentage: 0.25,
  hourlyRateExtraTime: 45,
};

export const AVAILABLE_ADDONS: AddOnItem[] = [
  {
    id: "oven",
    name: "Deep Oven & Grill Racks",
    price: 45,
    durationMinutes: 45,
    category: "kitchen",
    description: "Complete interior grease degreasing, glass door cleaning, and rack soak.",
    iconName: "Flame",
  },
  {
    id: "fridge",
    name: "Inside Refrigerator & Freezer",
    price: 40,
    durationMinutes: 35,
    category: "kitchen",
    description: "Shelves sanitized, crisper bins washed, and expired item wipe-down.",
    iconName: "Refrigerator",
  },
  {
    id: "windows",
    name: "Interior Windows & Tracks (10 panes)",
    price: 55,
    durationMinutes: 45,
    category: "interior",
    description: "Streak-free glass cleaning, interior sills, and vacuumed slider tracks.",
    iconName: "Maximize2",
  },
  {
    id: "cabinets",
    name: "Inside Kitchen Cabinets (Empty)",
    price: 50,
    durationMinutes: 45,
    category: "kitchen",
    description: "Interior shelf wipe-down, crumb extraction, and cabinet front polish.",
    iconName: "Layers",
  },
  {
    id: "baseboards",
    name: "Hand-Scrubbed Baseboards Detail",
    price: 45,
    durationMinutes: 40,
    category: "interior",
    description: "Full-perimeter hand scrub of trim, floor molding, and door frames.",
    iconName: "Sparkles",
  },
  {
    id: "pethair",
    name: "Heavy Pet Hair Deep Extraction",
    price: 35,
    durationMinutes: 30,
    category: "specialty",
    description: "Rubberized vacuum rake on upholstered couches, carpets, and baseboard nooks.",
    iconName: "Dog",
  },
];

export const NASSAU_TOWNS = [
  { name: "Massapequa", zip: "11758", territory: "South Shore" },
  { name: "Massapequa Park", zip: "11762", territory: "South Shore" },
  { name: "Garden City", zip: "11530", territory: "Central Nassau" },
  { name: "Syosset", zip: "11791", territory: "North Shore" },
  { name: "Merrick", zip: "11566", territory: "South Shore" },
  { name: "Rockville Centre", zip: "11570", territory: "South Shore" },
  { name: "Great Neck", zip: "11021", territory: "North Shore" },
  { name: "Plainview", zip: "11803", territory: "Mid Island" },
  { name: "Bellmore", zip: "11710", territory: "South Shore" },
  { name: "Jericho", zip: "11753", territory: "North Shore" },
  { name: "Long Beach", zip: "11561", territory: "Barrier Island" },
  { name: "Manhasset", zip: "11030", territory: "North Shore" },
];

export const INITIAL_TEAMS: CleaningTeam[] = [
  {
    id: "team-1",
    name: "South Shore Crew (Team 1)",
    leadName: "Maria Gonzalez",
    phone: "(516) 555-0142",
    color: "#635bff",
    maxDailyJobs: 3,
    active: true,
    serviceTerritory: "Massapequa, Merrick, Bellmore, RVC, Long Beach",
  },
  {
    id: "team-2",
    name: "North Shore & Central Crew (Team 2)",
    leadName: "David Rodriguez",
    phone: "(516) 555-0188",
    color: "#00d4b2",
    maxDailyJobs: 3,
    active: true,
    serviceTerritory: "Garden City, Syosset, Plainview, Great Neck, Jericho",
  },
];

export const SAMPLE_INITIAL_BOOKINGS: BookingRecord[] = [
  {
    id: "BK-8921",
    bookingReference: "NC-2026-0892",
    customer: {
      firstName: "Jennifer",
      lastName: "Callahan",
      email: "jcallahan@gmail.com",
      phone: "(516) 555-3819",
      streetAddress: "142 Ocean Avenue",
      city: "Massapequa",
      zipCode: "11758",
      accessInstructions: "Keypad code 4892# at side porch entrance.",
      specialNotes: "Golden Retriever locked in master bedroom during visit.",
    },
    serviceDate: "2026-09-15",
    timeSlot: "08:30 AM - 12:00 PM",
    assignedTeamId: "team-1",
    assignedTeamName: "South Shore Crew (Team 1)",
    pricing: {
      basePrice: 120,
      bedrooms: 4,
      bedroomPrice: 100,
      bathrooms: 2.5,
      bathroomPrice: 87.5,
      squareFeet: 2600,
      sqftPrice: 65,
      cleaningType: "deep",
      typeMultiplier: 1.45,
      homeCondition: "heavy",
      conditionMultiplier: 1.25,
      conditionExtraHours: 1.5,
      addOnsTotal: 85,
      addOnsSelected: [
        { id: "oven", name: "Deep Oven & Grill Racks", price: 45, durationMinutes: 45 },
        { id: "fridge", name: "Inside Refrigerator & Freezer", price: 40, durationMinutes: 35 },
      ],
      rawTotalBeforeDiscount: 662.5,
      frequency: "biweekly",
      frequencyDiscountPercent: 15,
      discountAmount: 99.38,
      finalTotal: 563.12,
      depositRequired: 140.78,
      balanceDueOnCompletion: 422.34,
      estimatedLaborHours: 5.5,
      calculationBasis: "(Base $120 + 4 Beds $100 + 2.5 Baths $87.50 + SqFt $65) x Deep 1.45 x Heavy 1.25 + Add-ons $85 - Bi-weekly 15% discount",
    },
    payment: {
      type: "deposit",
      amountPaid: 140.78,
      balanceDue: 422.34,
      paymentMethod: "stripe_card",
      stripePaymentIntentId: "pi_3MtwL2KZvN8Z4k1209ABcd",
      paidAt: "2026-09-13T16:20:00Z",
    },
    smsAlertsSent: [
      {
        id: "SMS-101",
        bookingId: "BK-8921",
        type: "CONFIRMATION",
        recipient: "CUSTOMER",
        phone: "(516) 555-3819",
        messageText: "Hi Jennifer! Your Deep Cleaning is confirmed for Tue Sep 15 at 8:30 AM. Team 1 (Maria G.) will arrive in Massapequa. Deposit of $140.78 received. Reply HELP for assistance.",
        sentTimestamp: "2026-09-13T16:20:05Z",
        deliveryStatus: "DELIVERED",
      },
      {
        id: "SMS-102",
        bookingId: "BK-8921",
        type: "TEAM_DISPATCH",
        recipient: "TEAM",
        phone: "(516) 555-0142",
        messageText: "DISPATCH ALERT: Tue Sep 15, 8:30 AM @ 142 Ocean Ave, Massapequa. 4-bed 2.5-bath Deep Clean with Oven & Fridge. Entry code: 4892#.",
        sentTimestamp: "2026-09-13T16:20:08Z",
        deliveryStatus: "DELIVERED",
      },
    ],
    status: "confirmed",
    createdAt: "2026-09-13T16:20:00Z",
  },
  {
    id: "BK-8922",
    bookingReference: "NC-2026-0893",
    customer: {
      firstName: "Michael",
      lastName: "Stern",
      email: "mstern@optonline.net",
      phone: "(516) 555-9182",
      streetAddress: "77 Stewart Avenue",
      city: "Garden City",
      zipCode: "11530",
      accessInstructions: "Doorman building, sign in under Stern unit 4B.",
    },
    serviceDate: "2026-09-16",
    timeSlot: "01:00 PM - 04:30 PM",
    assignedTeamId: "team-2",
    assignedTeamName: "North Shore & Central Crew (Team 2)",
    pricing: {
      basePrice: 120,
      bedrooms: 3,
      bedroomPrice: 75,
      bathrooms: 2,
      bathroomPrice: 70,
      squareFeet: 1800,
      sqftPrice: 30,
      cleaningType: "standard",
      typeMultiplier: 1.0,
      homeCondition: "normal",
      conditionMultiplier: 1.0,
      conditionExtraHours: 0,
      addOnsTotal: 55,
      addOnsSelected: [
        { id: "windows", name: "Interior Windows & Tracks (10 panes)", price: 55, durationMinutes: 45 },
      ],
      rawTotalBeforeDiscount: 350,
      frequency: "weekly",
      frequencyDiscountPercent: 20,
      discountAmount: 70,
      finalTotal: 280,
      depositRequired: 70,
      balanceDueOnCompletion: 210,
      estimatedLaborHours: 3.5,
      calculationBasis: "(Base $120 + 3 Beds $75 + 2 Baths $70 + SqFt $30) x Standard 1.0 + Windows $55 - Weekly 20% discount",
    },
    payment: {
      type: "full",
      amountPaid: 280,
      balanceDue: 0,
      paymentMethod: "stripe_card",
      stripePaymentIntentId: "pi_3MtwN9KZvN8Z4k8810EFgh",
      paidAt: "2026-09-14T09:15:00Z",
    },
    smsAlertsSent: [
      {
        id: "SMS-103",
        bookingId: "BK-8922",
        type: "CONFIRMATION",
        recipient: "CUSTOMER",
        phone: "(516) 555-9182",
        messageText: "Hi Michael! Your Weekly Standard Cleaning is booked for Wed Sep 16 at 1:00 PM in Garden City. Team 2 (David R.) is assigned. Paid in full $280.00.",
        sentTimestamp: "2026-09-14T09:15:05Z",
        deliveryStatus: "DELIVERED",
      },
    ],
    status: "confirmed",
    createdAt: "2026-09-14T09:15:00Z",
  },
];
